# Generated by Django 4.1.4 on 2099-02-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to='videos'),
        ),
    ]
