# Generated by Django 4.1.4 on 2099-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video_App', '0003_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='image',
        ),
    ]
